<a href="https://colab.research.google.com/github/khacthiennguyen/D8-Algothims/blob/main/T%C3%ADnh_t%C3%ADch_l%C5%A9y_d%C3%B2ng_ch%E1%BA%A3y_b%E1%BA%B1ng_D8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

In [33]:
docao= [[78, 72, 69, 71, 58, 49],
[74, 67, 58, 49, 46, 50],
[69, 53, 44, 37, 38, 48],
[64, 58, 55, 22, 31, 24],
[68, 81, 47, 21, 16, 19],
[74, 53, 34, 12, 11, 12]]

docao

[[78, 72, 69, 71, 58, 49],
 [74, 67, 58, 49, 46, 50],
 [69, 53, 44, 37, 38, 48],
 [64, 58, 55, 22, 31, 24],
 [68, 81, 47, 21, 16, 19],
 [74, 53, 34, 12, 11, 12]]

# **Hướng dòng chảy**

In [35]:
mdong = len(docao)
ncot = len(docao[0])
print (mdong,ncot)

6 6


In [36]:
DIR = np.zeros((mdong,ncot))
DIR

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
def Lancan(dong, cot, mdong, ncot):
  neighbor = []
  for i in range(-1, 2): # dong: -1, 0, +1
    for j in range(-1, 2):
      x = dong + i
      y = cot + j
      if (not((i == 0) and (j == 0))
      and ((x>=0) and (x<mdong) and (y>=0) and (y<ncot))):
                                neighbor.append((x,y))
  return neighbor

In [39]:
Lancan(5,3,6,6)

[(4, 2), (4, 3), (4, 4), (5, 2), (5, 4)]

In [40]:
def getCode (dX,dY):

  if (dX == 0 and dY == 1) : return 1
  if (dX == 0 and dY == -1) : return 16
  if (dX == -1 and dY == 0) : return 64
  if (dX == 1 and dY == 0) : return 4
  if (dX == 1 and dY == 1) : return 2
  if (dX == 1 and dY == -1) : return 8
  if (dX == -1 and dY == 1) : return 128
  if (dX == -1 and dY == -1) : return 32


In [42]:
def getDirection(dong,cot):
  danhsach_lc = Lancan(dong,cot,mdong,ncot)
  chenhlechmax = 0
  vitrix = 0
  vitriy=0
  for lc in danhsach_lc:
    import math
    dX = lc[0] - dong
    dY = lc[1] - cot
    kc = math.sqrt(dX ** 2 + dY ** 2)
    gtri = ( docao[dong][cot] - docao[lc[0]][lc[1]] )/kc
    if gtri > chenhlechmax:
      chenhlechmax = gtri
      vitrix = dX
      vitriy = dY
  return vitrix, vitriy

In [43]:
def calDirection():
  for i in range (mdong):
    for j in range (ncot):
      d = getDirection(i,j)
      DIR [i][j] = getCode(d[0],d[1])

In [44]:
DIR

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
calDirection()

In [46]:
DIR

array([[  2.,   2.,   2.,   4.,   4.,   8.],
       [  2.,   2.,   2.,   4.,   4.,   8.],
       [  1.,   1.,   2.,   4.,   8.,   4.],
       [128., 128.,   1.,   2.,   4.,   8.],
       [  2.,   1.,   1.,   4.,   4.,   4.],
       [  1.,   1.,   1.,   1.,  nan,  16.]])

array([[ 12.,  14.,  16.,  18.,  22.,  26.],
       [ 11.,  10.,  12.,  14.,  18.,  22.],
       [ 10.,   9.,   8.,  10.,  14.,  16.],
       [137., 136.,   7.,   6.,   8.,  12.],
       [  5.,   7.,   6.,   5.,   4.,  20.],
       [  4.,   3.,   2.,   1.,   0.,  16.]])

# **Tích Lũy Dòng Chảy**

In [72]:
LANCAN = np.array([[32,64,128],
                   [16,0,1],
                   [8,4,2]])
LANCAN

array([[ 32,  64, 128],
       [ 16,   0,   1],
       [  8,   4,   2]])

In [86]:
def tinh_tichluy(dong,cot):
  if table_test[dong][cot] == 0:
    global all
  table_test[dong][cot] =1
  hangxom = Lancan(dong,cot,mdong,ncot)
  for hx  in hangxom:
    if DIR[hx[0]][hx[1]] == LANCAN[1-hx[0]+dong] [1-hx[1]+cot]:
      all = all+1
      #print ("hang xom: [",hx[0],hx[1],"]")
      tinh_tichluy(hx[0],hx[1])

In [87]:
all = 0

In [88]:
table_test = np.zeros((mdong,ncot))

In [89]:
all

0

In [90]:
TICHLUY = np.zeros((mdong,ncot))

In [91]:
for i in range (mdong):
  for j in range (ncot):
    table_test= np.zeros((mdong,ncot))
    all = 0
    tinh_tichluy(i,j)
    TICHLUY[i][j] = all

In [92]:
TICHLUY

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  2.,  2.,  0.],
       [ 0.,  3.,  7.,  5.,  4.,  0.],
       [ 0.,  0.,  0., 20.,  0.,  1.],
       [ 0.,  0.,  1.,  2., 24.,  0.],
       [ 0.,  2.,  3.,  7., 35.,  1.]])